import { extendTheme, withDefaultColorScheme } from '@chakra-ui/react';

import * as components from './components';

export const theme = extendTheme(
  {
    // see: https://chakra-ui.com/docs/styled-system/customize-theme
    colors: {
      quacker: {
        // generated by: https://ei7ek.csb.app/
        50: '#e9f7ec',
        100: '#d5f0db',
        200: '#aee0b9',
        300: '#8ad19a',
        400: '#6ac17e',
        500: '#4eb264',
        600: '#4e8e5c',
        700: '#476b4f',
        800: '#37473b',
        900: '#202420',
      },
      purple: {
        50: '#f9dff3',
        100: '#f4c0e7',
        200: '#e881d0',
        300: '#dd42b8',
        400: '#b42091',
        500: '#75155e',
        600: '#5e114b',
        700: '#460d38',
        800: '#2f0826',
        900: '#170413',
      },
    },
    components: {
      ...components,
    },
  },
  withDefaultColorScheme({ colorScheme: 'blue' }),
);
